name: Build APK  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v3  

    - name: Set up Python  
      uses: actions/setup-python@v3  
      with:  
        python-version: '3.9'  

    - name: Cache Buildozer dependencies  
      uses: actions/cache@v3  
      with:  
        path: .buildozer_cache  
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}  

    - name: Install dependencies  
      run: |  
        sudo apt-get update  
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good  

    - name: Install Python dependencies  
      run: |  
        pip3 install --upgrade Cython==0.29.33 virtualenv buildozer  
        pip3 install -r requirements.txt  

    - name: Build APK  
      run: |  
        buildozer android debug  

    - name: Upload APK  
      uses: actions/upload-artifact@v3  
      with:  
        name: app-debug  
        path: bin/*.apk  
        
    - name: Create Release  
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  
      uses: softprops/action-gh-release@v1  
      with:  
        files: bin/*.apk  
        tag_name: v${{ github.run_number }}  
        name: Release ${{ github.run_number }}  
        draft: false  
        prerelease: false  
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
